interface Command
interface DocumentStorage
interface DocumentSerializer

Editor -d-> Document
Editor -d-> UserInterface
Editor -d-> DocumentStorage
Document --> DocumentSerializer
Command <|.. EditCommand
Command <|.. ExchangeCommand
Command <|.. DeleteCommand
Command <|.. SetActiveLineCommand
Command <|.. ExitCommand
Command <|.. SaveCommand
Command <|.. LoadCommand
DocumentStorage <|.. FileManagerAdapter
DocumentSerializer <|.. SimpleSerializer
FileManagerAdapter --> FileManager
EditCommand -u-> UserInterface
ExchangeCommand -u-> UserInterface
DeleteCommand -u-> UserInterface
SetActiveLineCommand -u-> UserInterface
SaveCommand -u-> UserInterface
SaveCommand --> DocumentStorage
LoadCommand -u-> UserInterface
LoadCommand --> DocumentStorage