hide circle
hide empty members

class "Edlin" as PROGRAMA {
    main()
}

class "Datos" as MODELO {
    document[]
    activeLine
}

class "Operaciones" as CONTROLADOR {
    processActions()
    ....
    ...
}

class "Presentación" as VISTA {
    print()
    ....
    ...
}

PROGRAMA -d-> MODELO : usa
CONTROLADOR -l-> MODELO : modifica
VISTA -r-> MODELO : consulta
PROGRAMA -d-> CONTROLADOR : llama
PROGRAMA -d-> VISTA : llama
